Set color to m/r*
set cursor off
clear

Set color to w/m
@ 00,00 say '                          '
@ 01,00 say '                          '
@ 02,00 say '                          '
@ 03,00 say '                          '
@ 04,00 say '                          '
@ 05,00 say '                          '
@ 06,00 say '                          '
@ 07,00 say '                          '
@ 08,00 say '                          '
@ 09,00 say '                          '
@ 10,00 say '                          '
@ 11,00 say '                          '
@ 12,00 say '                          '
@ 13,00 say '                          '
@ 14,00 say '                          '
@ 15,00 say '                          '
@ 16,00 say '                          '
@ 17,00 say '                          '
@ 18,00 say '                          '
@ 19,00 say '                          '
@ 20,00 say '                          '
@ 21,00 say '                          '
@ 22,00 say '                          '
@ 23,00 say '                          '
@ 24,00 say '                          '

Set color to w/gr*
@ 00,26 say '                            '
@ 01,26 say '                            '
@ 02,26 say '                            '
@ 03,26 say '                            '
@ 04,26 say '                            '
@ 05,26 say '                            '
@ 06,26 say '                            '
@ 07,26 say '                            '
@ 08,26 say '                            '
@ 09,26 say '                            '
@ 10,26 say '                            '
@ 11,26 say '                            '
@ 12,26 say '                            '
@ 13,26 say '                            '
@ 14,26 say '                            '
@ 15,26 say '                            '
@ 16,26 say '                            '
@ 17,26 say '                            '
@ 18,26 say '                            '
@ 19,26 say '                            '
@ 20,26 say '                            '
@ 21,26 say '                            '
@ 22,26 say '                            '
@ 23,26 say '                            '
@ 24,26 say '                            '
InKey(0)
clear
