Set color to m/r*
set cursor off
clear

Set color to w/b*
@ 00,00 say '                           '
@ 01,00 say '                           '
@ 02,00 say '                           '
@ 03,00 say '                           '
@ 04,00 say '                           '
@ 05,00 say '                           '
@ 06,00 say '                           '
@ 07,00 say '                           '
@ 08,00 say '                           '
@ 09,00 say '                           '
@ 10,00 say '                           '
@ 11,00 say '                           '
@ 12,00 say '                           '
@ 13,00 say '                           '
@ 14,00 say '                           '
@ 15,00 say '                           '
@ 16,00 say '                           '
@ 17,00 say '                           '
@ 18,00 say '                           '
@ 19,00 say '                           '
@ 20,00 say '                           '
@ 21,00 say '                           '
@ 22,00 say '                           '
@ 23,00 say '                           '
@ 24,00 say '                           '

Set color to w/w*
@ 00,27 say '                            '
@ 01,27 say '                            '
@ 02,27 say '                            '
@ 03,27 say '                            '
@ 04,27 say '                            '
@ 05,27 say '                            '
@ 06,27 say '                            '
@ 07,27 say '                            '
@ 08,27 say '                            '
@ 09,27 say '                            '
@ 10,27 say '                            '
@ 11,27 say '                            '
@ 12,27 say '                            '
@ 13,27 say '                            '
@ 14,27 say '                            '
@ 15,27 say '                            '
@ 16,27 say '                            '
@ 17,27 say '                            '
@ 18,27 say '                            '
@ 19,27 say '                            '
@ 20,27 say '                            '
@ 21,27 say '                            '
@ 22,27 say '                            '
@ 23,27 say '                            '
@ 24,27 say '                            '
InKey(0)
clear

